In [1]:
import polars as pl

In [15]:
df = pl.read_parquet('data/2022.parquet')

In [10]:
bobaadr = pl.read_csv('data/pad/bobaadr.txt')
bobaadr.head()

shape: (5, 26)
┌──────┬───────┬─────┬─────────┬─────┬─────────────┬─────────┬─────────┬─────────────┐
│ boro ┆ block ┆ lot ┆ bin     ┆ ... ┆ b10sc       ┆ segid   ┆ zipcode ┆ physical_id │
│ ---  ┆ ---   ┆ --- ┆ ---     ┆     ┆ ---         ┆ ---     ┆ ---     ┆ ---         │
│ i64  ┆ i64   ┆ i64 ┆ i64     ┆     ┆ i64         ┆ str     ┆ str     ┆ str         │
╞══════╪═══════╪═════╪═════════╪═════╪═════════════╪═════════╪═════════╪═════════════╡
│ 1    ┆ 1     ┆ 10  ┆ 1000000 ┆ ... ┆ 10077201010 ┆ 0117705 ┆ 10004   ┆ 0138883     │
├╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 1    ┆ 1     ┆ 10  ┆ 1000000 ┆ ... ┆ 10077301010 ┆ 0115073 ┆ 10004   ┆ 0175748     │
├╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 1    ┆ 1     ┆ 10  ┆ 1000000 ┆ ... ┆ 10077401010 ┆ 0018085 ┆ 10004   ┆ 0097424     │
├╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 1    ┆ 1     ┆ 10  ┆ 1000000 ┆ ... ┆ 10077501010 ┆ 0299272 ┆ 10004   ┆ 0174909     │
├╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 1    ┆ 1     ┆ 10  ┆ 1000000 ┆ ... ┆ 10077601010 ┆ 0317315 ┆ 10004   ┆ 0185204     │
└──────┴───────┴─────┴─────────┴─────┴─────────────┴─────────┴─────────┴─────────────┘

In [11]:
bobaadr.select(['sc5', 'scboro', 'hhnd', 'bin', 'physical_id', 'zipcode', 'stname']).write_parquet('./data/bobaadr.parquet')
bobaadr = pl.read_parquet('./data/bobaadr.parquet')

In [12]:
bobaadr = (bobaadr
  .unique(subset=['sc5', 'hhnd'])
  .select([
    pl.col('sc5').alias('Street Code'),
    pl.col('scboro').cast(pl.Utf8).cast(pl.Categorical).alias('Borough Code'),
    pl.col('hhnd').str.lstrip().alias('House Number'),
    pl.col('bin').alias('BIN'),
    pl.col('physical_id').cast(pl.Int64, strict=False).alias('PHYSICALID'),
    pl.col('stname'),
    pl.col('zipcode'),
  ])
)
bobaadr.head(1000).tail()

shape: (5, 7)
┌─────────────┬──────────────┬──────────────┬─────────┬────────────┬─────────────────────┬─────────┐
│ Street Code ┆ Borough Code ┆ House Number ┆ BIN     ┆ PHYSICALID ┆ stname              ┆ zipcode │
│ ---         ┆ ---          ┆ ---          ┆ ---     ┆ ---        ┆ ---                 ┆ ---     │
│ i64         ┆ cat          ┆ str          ┆ i64     ┆ i64        ┆ str                 ┆ str     │
╞═════════════╪══════════════╪══════════════╪═════════╪════════════╪═════════════════════╪═════════╡
│ 14410       ┆ 1            ┆ 11           ┆ 1001016 ┆ 103207     ┆ CEDAR STREET        ┆ 10005   │
├╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┤
│ 25630       ┆ 1            ┆ 94           ┆ 1001016 ┆ 748        ┆ MAIDEN LANE         ┆ 10038   │
├╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┤
│ 28870       ┆ 1            ┆ 45           ┆ 1000000 ┆ 182993     ┆ PINE STREET         ┆ 10005   │
├╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┤
│ 45440       ┆ 1            ┆ 49           ┆ 1000000 ┆ 822        ┆ WILLIAM STREET      ┆ 10005   │
├╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┤
│ 32910       ┆ 1            ┆ 46           ┆ 1001017 ┆ 161        ┆ WALL STREET         ┆ 10005   │
└─────────────┴──────────────┴──────────────┴─────────┴────────────┴─────────────────────┴─────────┘

In [17]:
df.shape

(12252095, 4)

In [16]:
df = (df
  .with_column(pl.col('House Number').fill_null(''))
  .select(['House Number', 'Street Code1'])
  .join(bobaadr.select(['Street Code', 'House Number', 'BIN', 'PHYSICALID']), left_on=['Street Code1', 'House Number'], right_on=['Street Code', 'House Number'], how='left')
  .join(bobaadr.select(['Street Code', 'Borough Code', 'zipcode']).unique(subset='Street Code'), left_on=['Street Code1'], right_on=['Street Code'], how='left')
  .drop(['Street Code1', 'House Number'])
)
df.head()

shape: (5, 4)
┌─────────┬────────────┬──────────────┬─────────┐
│ BIN     ┆ PHYSICALID ┆ Borough Code ┆ zipcode │
│ ---     ┆ ---        ┆ ---          ┆ ---     │
│ i64     ┆ i64        ┆ cat          ┆ str     │
╞═════════╪════════════╪══════════════╪═════════╡
│ 3251647 ┆ 182459     ┆ 2            ┆ 10465   │
├╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┤
│ null    ┆ null       ┆ 1            ┆ 10035   │
├╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┤
│ 3321974 ┆ 96408      ┆ 3            ┆ 11217   │
├╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┤
│ 3390265 ┆ 69802      ┆ 2            ┆ 10457   │
├╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┤
│ 3074052 ┆ 69083      ┆ 3            ┆ 11221   │
└─────────┴────────────┴──────────────┴─────────┘

In [8]:
ap = pl.read_csv('data/Address_Point.csv', ignore_errors=True)
ap.head()

shape: (5, 23)
┌─────────────────────────────┬──────────┬─────────┬──────┬─────┬─────┬──────┬──────┬──────────────┐
│ the_geom                    ┆ ADDRESS_ ┆ BIN     ┆ H_NO ┆ ... ┆ POS ┆ POST ┆ POST ┆ FULL_STREE   │
│ ---                         ┆ ID       ┆ ---     ┆ ---  ┆     ┆ T_T ┆ _DIR ┆ _MOD ┆ ---          │
│ str                         ┆ ---      ┆ i64     ┆ i64  ┆     ┆ YPE ┆ EC   ┆ IF   ┆ str          │
│                             ┆ i64      ┆         ┆      ┆     ┆ --- ┆ ---  ┆ ---  ┆              │
│                             ┆          ┆         ┆      ┆     ┆ str ┆ str  ┆ str  ┆              │
╞═════════════════════════════╪══════════╪═════════╪══════╪═════╪═════╪══════╪══════╪══════════════╡
│ POINT (-73.94890840262882   ┆ 3066687  ┆ 3053232 ┆ 54   ┆ ... ┆ ST  ┆ null ┆ null ┆ MACON ST     │
│ 40.681...                   ┆          ┆         ┆      ┆     ┆     ┆      ┆      ┆              │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ POINT (-73.94867469809614   ┆ 3064205  ┆ 3051113 ┆ 438  ┆ ... ┆ AVE ┆ null ┆ null ┆ GATES AVE    │
│ 40.686...                   ┆          ┆         ┆      ┆     ┆     ┆      ┆      ┆              │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ POINT (-73.95302508854085   ┆ 3063204  ┆ 3050344 ┆ 442  ┆ ... ┆ AVE ┆ null ┆ null ┆ GREENE AVE   │
│ 40.688...                   ┆          ┆         ┆      ┆     ┆     ┆      ┆      ┆              │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ POINT (-73.94380067421258   ┆ 3065757  ┆ 3052411 ┆ 411  ┆ ... ┆ AVE ┆ null ┆ null ┆ TOMPKINS AVE │
│ 40.683...                   ┆          ┆         ┆      ┆     ┆     ┆      ┆      ┆              │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ POINT (-73.9422673814714    ┆ 3066531  ┆ 3053096 ┆ 290  ┆ ... ┆ ST  ┆ null ┆ null ┆ HALSEY ST    │
│ 40.6825...                  ┆          ┆         ┆      ┆     ┆     ┆      ┆      ┆              │
└─────────────────────────────┴──────────┴─────────┴──────┴─────┴─────┴──────┴──────┴──────────────┘

In [9]:
ap.select(['the_geom', 'BIN', 'PHYSICALID', 'BOROCODE']).write_parquet('./data/address_point.parquet')
ap = pl.read_parquet('./data/address_point.parquet')

In [ ]:
ap = (ap
  .with_columns([
    pl.col('the_geom').str.slice(7).str.replace(' .*', '').cast(pl.Float64).alias('lng'),
    pl.col('the_geom').str.replace('.* ', '').str.replace('\)', '').cast(pl.Float64).alias('lat'),
  ])
  .select(['BIN', 'PHYSICALID', 'BOROCODE', 'lng', 'lat'])
)
ap.head()

shape: (5, 5)
┌─────────┬────────────┬──────────┬────────────┬───────────┐
│ BIN     ┆ PHYSICALID ┆ BOROCODE ┆ lng        ┆ lat       │
│ ---     ┆ ---        ┆ ---      ┆ ---        ┆ ---       │
│ i64     ┆ i64        ┆ i64      ┆ f64        ┆ f64       │
╞═════════╪════════════╪══════════╪════════════╪═══════════╡
│ 3053232 ┆ 66261      ┆ 3        ┆ -73.948908 ┆ 40.681025 │
├╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 3051113 ┆ 68956      ┆ 3        ┆ -73.948675 ┆ 40.686299 │
├╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 3050344 ┆ 44078      ┆ 3        ┆ -73.953025 ┆ 40.688052 │
├╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 3052411 ┆ 117570     ┆ 3        ┆ -73.943801 ┆ 40.683479 │
├╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 3053096 ┆ 79555      ┆ 3        ┆ -73.942267 ┆ 40.6825   │
└─────────┴────────────┴──────────┴────────────┴───────────┘

In [ ]:
df = (df
  .join(ap, on=['BIN', 'PHYSICALID'])
  .drop(['BIN', 'PHYSICALID'])
)

shape: (4295556, 8)
┌────────────┬───────────┬─────────┬────────┬────────────┬──────────┬────────────┬───────────┐
│ House      ┆ Street    ┆ BIN     ┆ PHYSIC ┆ Borough    ┆ BOROCODE ┆ lng        ┆ lat       │
│ Number     ┆ Code      ┆ ---     ┆ ALID   ┆ Code       ┆ ---      ┆ ---        ┆ ---       │
│ ---        ┆ ---       ┆ i64     ┆ ---    ┆ ---        ┆ i64      ┆ f64        ┆ f64       │
│ str        ┆ i64       ┆         ┆ i64    ┆ cat        ┆          ┆            ┆           │
╞════════════╪═══════════╪═════════╪════════╪════════════╪══════════╪════════════╪═══════════╡
│ 100        ┆ 63430     ┆ 3251647 ┆ 182459 ┆ 2          ┆ 3        ┆ -73.976366 ┆ 40.6952   │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 170        ┆ 79430     ┆ 3321974 ┆ 96408  ┆ 3          ┆ 3        ┆ -73.974159 ┆ 40.684166 │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 22         ┆ 53130     ┆ 3390265 ┆ 69802  ┆ 2          ┆ 3        ┆ -73.934426 ┆ 40.697618 │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 25         ┆ 81030     ┆ 3074052 ┆ 69083  ┆ 3          ┆ 3        ┆ -73.925975 ┆ 40.695213 │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ ...        ┆ ...       ┆ ...     ┆ ...    ┆ ...        ┆ ...      ┆ ...        ┆ ...       │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 74         ┆ 52830     ┆ 3064528 ┆ 64766  ┆ 3          ┆ 3        ┆ -73.958554 ┆ 40.731136 │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 74         ┆ 52830     ┆ 3064528 ┆ 64766  ┆ 3          ┆ 3        ┆ -73.958456 ┆ 40.731145 │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 77         ┆ 61130     ┆ 3064800 ┆ 88245  ┆ 3          ┆ 3        ┆ -73.957785 ┆ 40.729238 │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 1139       ┆ 23930     ┆ 3076964 ┆ 47559  ┆ 3          ┆ 3        ┆ -73.917966 ┆ 40.689624 │
└────────────┴───────────┴─────────┴────────┴────────────┴──────────┴────────────┴───────────┘